import type { Design } from "./types";

export const mockDesigns: Design[] = [
  {
    id: "design-382",
    src: "https://images.unsplash.com/photo-1618219667957-57bcae695603?auto=format&fit=crop&w=1000&q=80",
    title: "Brown wooden framed white padded armchair beside brown wooden table",
    description: "brown wooden framed white padded armchair beside brown wooden table",
    style: "scandinavian",
    room: "living_room",
    palette: "warm",
    budget: "low",
    lighting: "daylight",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: true,
    hasPlants: false,
    floorType: "wood",
    theme: "cozy",
    qualityScore: 8,
  },
  {
    id: "design-4",
    src: "https://images.unsplash.com/photo-1599696848652-f0ff23bc911f?auto=format&fit=crop&w=1000&q=80",
    title: "Brown and white couch beside window",
    description: "brown and white couch beside window",
    style: "scandinavian",
    room: "living_room",
    palette: "warm",
    budget: "low",
    lighting: "daylight",
    material: "textile",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: true,
    hasPlants: false,
    floorType: "wood",
    theme: "cozy",
    qualityScore: 7,
  },
  {
    id: "design-124",
    src: "https://images.unsplash.com/photo-1618221710640-c0eaaa2adb49?auto=format&fit=crop&w=1000&q=80",
    title: "White and brown living room set",
    description: "white and brown living room set",
    style: "scandinavian",
    room: "living_room",
    palette: "neutral",
    budget: "low",
    lighting: "soft",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "cozy",
    qualityScore: 6,
  },
  {
    id: "design-84",
    src: "https://images.unsplash.com/photo-1618221639244-c1a8502c0eb9?auto=format&fit=crop&w=1000&q=80",
    title: "White and brown wooden table and chairs",
    description: "white and brown wooden table and chairs",
    style: "scandinavian",
    room: "dining_room",
    palette: "neutral",
    budget: "low",
    lighting: "soft",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "cozy",
    qualityScore: 8,
  },
  {
    id: "design-304",
    src: "https://images.unsplash.com/photo-1633505650701-6104c4fc72c2?auto=format&fit=crop&w=1000&q=80",
    title: "A bedroom with a large bed in a room",
    description: "a bedroom with a large bed in a room",
    style: "scandinavian",
    room: "bedroom",
    palette: "warm",
    budget: "low",
    lighting: "soft",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "cozy",
    qualityScore: 7,
  },
  {
    id: "design-337",
    src: "https://images.unsplash.com/photo-1600210491305-7396500b5b31?auto=format&fit=crop&w=1000&q=80",
    title: "White and blue bed linen",
    description: "white and blue bed linen",
    style: "scandinavian",
    room: "bedroom",
    palette: "cool",
    budget: "low",
    lighting: "soft",
    material: "textile",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "cozy",
    qualityScore: 4,
  },
  {
    id: "design-190",
    src: "https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1000&q=80",
    title: "Green and white wooden dining table and chairs",
    description: "green and white wooden dining table and chairs",
    style: "scandinavian",
    room: "dining_room",
    palette: "neutral",
    budget: "low",
    lighting: "daylight",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: true,
    hasPlants: true,
    floorType: "wood",
    theme: "cozy",
    qualityScore: 6,
  },
  {
    id: "design-60",
    src: "https://images.unsplash.com/photo-1502005097973-6a7082348e28?auto=format&fit=crop&w=1000&q=80",
    title: "White wooden kitchen island and cupboard cabinets near glass panel door",
    description: "white wooden kitchen island and cupboard cabinets near glass panel door",
    style: "scandinavian",
    room: "kitchen",
    palette: "neutral",
    budget: "medium",
    lighting: "daylight",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: true,
    hasPlants: false,
    floorType: "wood",
    theme: "cozy",
    qualityScore: 5,
  },
  {
    id: "design-56",
    src: "https://images.unsplash.com/photo-1581783458534-001a466b5487?auto=format&fit=crop&w=1000&q=80",
    title: "White ceramic sink beside window",
    description: "white ceramic sink beside window",
    style: "scandinavian",
    room: "bathroom",
    palette: "neutral",
    budget: "low",
    lighting: "daylight",
    material: "stone",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: true,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 5,
  },
  {
    id: "design-63",
    src: "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&w=1000&q=80",
    title: "Brown staircase",
    description: "brown staircase",
    style: "scandinavian",
    room: "hallway",
    palette: "warm",
    budget: "low",
    lighting: "soft",
    material: "wood",
    orientation: "vertical",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "cozy",
    qualityScore: 5,
  },
  {
    id: "design-3",
    src: "https://images.unsplash.com/photo-1631679706909-1844bbd07221?auto=format&fit=crop&w=1000&q=80",
    title: "A living room filled with furniture and a mirror",
    description: "a living room filled with furniture and a mirror",
    style: "modern",
    room: "living_room",
    palette: "cool",
    budget: "medium",
    lighting: "ambient",
    material: "mixed",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 5,
  },
  {
    id: "design-150",
    src: "https://images.unsplash.com/photo-1649511134921-67afc567280c?auto=format&fit=crop&w=1000&q=80",
    title: "A living room filled with furniture and a painting on the wall",
    description: "a living room filled with furniture and a painting on the wall",
    style: "modern",
    room: "living_room",
    palette: "neutral",
    budget: "medium",
    lighting: "soft",
    material: "mixed",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 6,
  },
  {
    id: "design-162",
    src: "https://images.unsplash.com/photo-1587316205943-b15dc52a12e0?auto=format&fit=crop&w=1000&q=80",
    title: "Black leather couch beside green potted plant",
    description: "black leather couch beside green potted plant",
    style: "modern",
    room: "living_room",
    palette: "cool",
    budget: "medium",
    lighting: "soft",
    material: "textile",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: true,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 6,
  },
  {
    id: "design-369",
    src: "https://images.unsplash.com/photo-1618221118493-9cfa1a1c00da?auto=format&fit=crop&w=1000&q=80",
    title: "White bed linen with white pillow",
    description: "white bed linen with white pillow",
    style: "modern",
    room: "bedroom",
    palette: "neutral",
    budget: "medium",
    lighting: "soft",
    material: "textile",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 6,
  },
  {
    id: "design-217",
    src: "https://images.unsplash.com/photo-1616486701797-0f33f61038ec?auto=format&fit=crop&w=1000&q=80",
    title: "White and black dining table and chairs",
    description: "white and black dining table and chairs",
    style: "modern",
    room: "dining_room",
    palette: "cool",
    budget: "medium",
    lighting: "ambient",
    material: "metal",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 6,
  },
  {
    id: "design-364",
    src: "https://images.unsplash.com/photo-1571843439991-dd2b8e051966?auto=format&fit=crop&w=1000&q=80",
    title: "A kitchen with a center island with stools",
    description: "a kitchen with a center island with stools",
    style: "modern",
    room: "kitchen",
    palette: "neutral",
    budget: "medium",
    lighting: "ambient",
    material: "stone",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 5,
  },
  {
    id: "design-249",
    src: "https://images.unsplash.com/photo-1526887593587-a307ea5d46b4?auto=format&fit=crop&w=1000&q=80",
    title: "Turned on flat screen monitor and laptop on desk",
    description: "turned on flat screen monitor and laptop on desk",
    style: "modern",
    room: "office",
    palette: "cool",
    budget: "medium",
    lighting: "ambient",
    material: "metal",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 5,
  },
  {
    id: "design-443",
    src: "https://images.unsplash.com/photo-1668067611084-80ce6db6bbe9?auto=format&fit=crop&w=1000&q=80",
    title: "A staircase with a chair",
    description: "a staircase with a chair",
    style: "modern",
    room: "hallway",
    palette: "cool",
    budget: "medium",
    lighting: "ambient",
    material: "metal",
    orientation: "vertical",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 5,
  },
  {
    id: "design-297",
    src: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1000&q=80",
    title: "White ceramic bathtub",
    description: "white ceramic bathtub",
    style: "modern",
    room: "bathroom",
    palette: "neutral",
    budget: "medium",
    lighting: "soft",
    material: "stone",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 5,
  },
  {
    id: "design-46",
    src: "https://images.unsplash.com/photo-1618221469555-7f3ad97540d6?auto=format&fit=crop&w=1000&q=80",
    title: "White wooden table with chairs",
    description: "white wooden table with chairs",
    style: "modern",
    room: "living_room",
    palette: "neutral",
    budget: "medium",
    lighting: "soft",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 6,
  },
  {
    id: "design-334",
    src: "https://images.unsplash.com/photo-1616594266774-769089710d76?auto=format&fit=crop&w=1000&q=80",
    title: "Brown wooden table and chairs",
    description: "brown wooden table and chairs",
    style: "minimal",
    room: "living_room",
    palette: "neutral",
    budget: "medium",
    lighting: "soft",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 9,
  },
  {
    id: "design-355",
    src: "https://images.unsplash.com/photo-1582417728413-b2347161b864?auto=format&fit=crop&w=1000&q=80",
    title: "Black wooden coffee table near white couch",
    description: "black wooden coffee table near white couch",
    style: "minimal",
    room: "living_room",
    palette: "neutral",
    budget: "medium",
    lighting: "soft",
    material: "mixed",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 7,
  },
  {
    id: "design-101",
    src: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1000&q=80",
    title: "White and gray floral sofa set",
    description: "white and gray floral sofa set",
    style: "minimal",
    room: "living_room",
    palette: "cool",
    budget: "medium",
    lighting: "soft",
    material: "textile",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 6,
  },
  {
    id: "design-257",
    src: "https://images.unsplash.com/photo-1531835551805-16d864c8d311?auto=format&fit=crop&w=1000&q=80",
    title: "Black platform bed with white mattress inside bedroom",
    description: "black platform bed with white mattress inside bedroom",
    style: "minimal",
    room: "bedroom",
    palette: "cool",
    budget: "medium",
    lighting: "soft",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 5,
  },
  {
    id: "design-514",
    src: "https://images.unsplash.com/photo-1610178167104-488495443e01?auto=format&fit=crop&w=1000&q=80",
    title: "White bathtub near white wall",
    description: "white bathtub near white wall",
    style: "minimal",
    room: "bathroom",
    palette: "neutral",
    budget: "medium",
    lighting: "soft",
    material: "stone",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 4,
  },
  {
    id: "design-51",
    src: "https://images.unsplash.com/photo-1537726235470-8504e3beef77?auto=format&fit=crop&w=1000&q=80",
    title: "Dining table set placed beside glass window",
    description: "dining table set placed beside glass window",
    style: "minimal",
    room: "dining_room",
    palette: "neutral",
    budget: "medium",
    lighting: "daylight",
    material: "mixed",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: true,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 5,
  },
  {
    id: "design-76",
    src: "https://images.unsplash.com/photo-1601907560526-d679c8ed95ce?auto=format&fit=crop&w=1000&q=80",
    title: "White and brown wooden staircase",
    description: "white and brown wooden staircase",
    style: "minimal",
    room: "hallway",
    palette: "neutral",
    budget: "medium",
    lighting: "soft",
    material: "wood",
    orientation: "vertical",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 3,
  },
  {
    id: "design-439",
    src: "https://images.unsplash.com/photo-1616486029423-aaa4789e8c9a?auto=format&fit=crop&w=1000&q=80",
    title: "Black laptop computer on white bed",
    description: "black laptop computer on white bed",
    style: "minimal",
    room: "office",
    palette: "neutral",
    budget: "medium",
    lighting: "soft",
    material: "mixed",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 5,
  },
  {
    id: "design-233",
    src: "https://images.unsplash.com/photo-1616046330109-09ee9e34be48?auto=format&fit=crop&w=1000&q=80",
    title: "Brown woven basket on brown wooden table",
    description: "brown woven basket on brown wooden table",
    style: "minimal",
    room: "kitchen",
    palette: "warm",
    budget: "low",
    lighting: "soft",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 4,
  },
  {
    id: "design-322",
    src: "https://images.unsplash.com/photo-1541533260371-b8fc9b596d84?auto=format&fit=crop&w=1000&q=80",
    title: "Yellow rolling chair near window",
    description: "yellow rolling chair near window",
    style: "minimal",
    room: "office",
    palette: "bright",
    budget: "medium",
    lighting: "daylight",
    material: "mixed",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: true,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 7,
  },
  {
    id: "design-273",
    src: "https://images.unsplash.com/photo-1632935190508-bd46801c14af?auto=format&fit=crop&w=1000&q=80",
    title: "A living room filled with furniture and a painting on the wall",
    description: "a living room filled with furniture and a painting on the wall",
    style: "japandi",
    room: "living_room",
    palette: "neutral",
    budget: "medium",
    lighting: "soft",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "cozy",
    qualityScore: 7,
  },
  {
    id: "design-171",
    src: "https://images.unsplash.com/photo-1558442086-8ea19a79cd4d?auto=format&fit=crop&w=1000&q=80",
    title: "Grey living room interior",
    description: "grey living room interior",
    style: "japandi",
    room: "living_room",
    palette: "neutral",
    budget: "medium",
    lighting: "soft",
    material: "mixed",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "cozy",
    qualityScore: 6,
  },
  {
    id: "design-194",
    src: "https://images.unsplash.com/photo-1537456204312-b6b74c785065?auto=format&fit=crop&w=1000&q=80",
    title: "Round brown wooden table and four white chairs",
    description: "round brown wooden table and four white chairs",
    style: "japandi",
    room: "living_room",
    palette: "warm",
    budget: "medium",
    lighting: "soft",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "cozy",
    qualityScore: 6,
  },
  {
    id: "design-187",
    src: "https://images.unsplash.com/photo-1540932428079-887d0d7a8fa5?auto=format&fit=crop&w=1000&q=80",
    title: "Brown cushion couch",
    description: "brown cushion couch",
    style: "japandi",
    room: "living_room",
    palette: "warm",
    budget: "medium",
    lighting: "soft",
    material: "textile",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "cozy",
    qualityScore: 6,
  },
  {
    id: "design-456",
    src: "https://images.unsplash.com/photo-1617098900591-3f90928e8c54?auto=format&fit=crop&w=1000&q=80",
    title: "White and black bed linen",
    description: "white and black bed linen",
    style: "japandi",
    room: "bedroom",
    palette: "neutral",
    budget: "medium",
    lighting: "soft",
    material: "textile",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "cozy",
    qualityScore: 5,
  },
  {
    id: "design-237",
    src: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=1000&q=80",
    title: "White kitchen room set",
    description: "white kitchen room set",
    style: "japandi",
    room: "kitchen",
    palette: "neutral",
    budget: "medium",
    lighting: "soft",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "cozy",
    qualityScore: 4,
  },
  {
    id: "design-480",
    src: "https://images.unsplash.com/photo-1533090368676-1fd25485db88?auto=format&fit=crop&w=1000&q=80",
    title: "Green plant on white pot beside white study lamp",
    description: "green plant on white pot beside white study lamp",
    style: "japandi",
    room: "office",
    palette: "neutral",
    budget: "medium",
    lighting: "soft",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: true,
    floorType: "wood",
    theme: "cozy",
    qualityScore: 5,
  },
  {
    id: "design-177",
    src: "https://images.unsplash.com/photo-1631701601945-414a32dbef47?auto=format&fit=crop&w=1000&q=80",
    title: "A living room filled with furniture and a mirror",
    description: "a living room filled with furniture and a mirror",
    style: "japandi",
    room: "living_room",
    palette: "neutral",
    budget: "medium",
    lighting: "soft",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "cozy",
    qualityScore: 6,
  },
  {
    id: "design-479",
    src: "https://images.unsplash.com/photo-1648536475110-55e22cab6159?auto=format&fit=crop&w=1000&q=80",
    title: "A dining room table with chairs and a chandelier",
    description: "a dining room table with chairs and a chandelier",
    style: "japandi",
    room: "dining_room",
    palette: "warm",
    budget: "medium",
    lighting: "ambient",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 5,
  },
  {
    id: "design-72",
    src: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1000&q=80",
    title: "Architectural photography of black and brown hallway",
    description: "architectural photography of black and brown hallway",
    style: "japandi",
    room: "hallway",
    palette: "warm",
    budget: "medium",
    lighting: "soft",
    material: "wood",
    orientation: "vertical",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 2,
  },
  {
    id: "design-258",
    src: "https://images.unsplash.com/photo-1532372576444-dda954194ad0?auto=format&fit=crop&w=1000&q=80",
    title: "Round grey moon chair with brown pillow on top",
    description: "round grey moon chair with brown pillow on top",
    style: "boho",
    room: "living_room",
    palette: "warm",
    budget: "medium",
    lighting: "soft",
    material: "textile",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "artistic",
    qualityScore: 6,
  },
  {
    id: "design-261",
    src: "https://images.unsplash.com/photo-1648993880083-3080b2110bc0?auto=format&fit=crop&w=1000&q=80",
    title: "A white room with a gold lamp and a wicker chair",
    description: "a white room with a gold lamp and a wicker chair",
    style: "boho",
    room: "living_room",
    palette: "warm",
    budget: "medium",
    lighting: "ambient",
    material: "textile",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "artistic",
    qualityScore: 6,
  },
  {
    id: "design-210",
    src: "https://images.unsplash.com/photo-1551298370-9d3d53740c72?auto=format&fit=crop&w=1000&q=80",
    title: "Yellow chair",
    description: "yellow chair",
    style: "boho",
    room: "living_room",
    palette: "bright",
    budget: "medium",
    lighting: "daylight",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: true,
    hasPlants: false,
    floorType: "wood",
    theme: "artistic",
    qualityScore: 6,
  },
  {
    id: "design-37",
    src: "https://images.unsplash.com/photo-1618221381711-42ca8ab6e908?auto=format&fit=crop&w=1000&q=80",
    title: "Orange and black sofa with throw pillows",
    description: "orange and black sofa with throw pillows",
    style: "boho",
    room: "living_room",
    palette: "warm",
    budget: "medium",
    lighting: "ambient",
    material: "textile",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "artistic",
    qualityScore: 6,
  },
  {
    id: "design-41",
    src: "https://images.unsplash.com/photo-1532323544230-7191fd51bc1b?auto=format&fit=crop&w=1000&q=80",
    title: "Wicker table and two chairs near swimming pool",
    description: "wicker table and two chairs near swimming pool",
    style: "boho",
    room: "balcony",
    palette: "warm",
    budget: "medium",
    lighting: "daylight",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: true,
    hasPlants: false,
    floorType: "wood",
    theme: "cozy",
    qualityScore: 5,
  },
  {
    id: "design-252",
    src: "https://images.unsplash.com/photo-1674542572845-7875fa71f1ca?auto=format&fit=crop&w=1000&q=80",
    title: "A dining room table with a vase of flowers on it",
    description: "a dining room table with a vase of flowers on it",
    style: "boho",
    room: "dining_room",
    palette: "warm",
    budget: "medium",
    lighting: "soft",
    material: "mixed",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "artistic",
    qualityScore: 4,
  },
  {
    id: "design-460",
    src: "https://images.unsplash.com/photo-1614590354333-c72a209c78a5?auto=format&fit=crop&w=1000&q=80",
    title: "Yellow flowers in brown woven basket on blue table",
    description: "yellow flowers in brown woven basket on blue table",
    style: "boho",
    room: "kitchen",
    palette: "bright",
    budget: "medium",
    lighting: "daylight",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: true,
    hasPlants: false,
    floorType: "wood",
    theme: "artistic",
    qualityScore: 4,
  },
  {
    id: "design-246",
    src: "https://images.unsplash.com/photo-1668067516409-f3bb960ab4a2?auto=format&fit=crop&w=1000&q=80",
    title: "A table with chairs around it",
    description: "a table with chairs around it",
    style: "boho",
    room: "living_room",
    palette: "warm",
    budget: "medium",
    lighting: "soft",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "artistic",
    qualityScore: 6,
  },
  {
    id: "design-470",
    src: "https://images.unsplash.com/photo-1617104678098-de229db51175?auto=format&fit=crop&w=1000&q=80",
    title: "Black and white bed linen",
    description: "black and white bed linen",
    style: "boho",
    room: "bedroom",
    palette: "neutral",
    budget: "medium",
    lighting: "soft",
    material: "textile",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "artistic",
    qualityScore: 5,
  },
  {
    id: "design-240",
    src: "https://images.unsplash.com/photo-1609081144289-eacc3108cd03?auto=format&fit=crop&w=1000&q=80",
    title: "White sofa near brown wooden chair",
    description: "white sofa near brown wooden chair",
    style: "boho",
    room: "living_room",
    palette: "warm",
    budget: "medium",
    lighting: "soft",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "artistic",
    qualityScore: 6,
  },
  {
    id: "design-278",
    src: "https://images.unsplash.com/photo-1737474707380-5ef35770d8a7?auto=format&fit=crop&w=1000&q=80",
    title: "A room with a chair and a desk in it",
    description: "a room with a chair and a desk in it",
    style: "loft",
    room: "office",
    palette: "cool",
    budget: "medium",
    lighting: "ambient",
    material: "metal",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "industrial",
    qualityScore: 6,
  },
  {
    id: "design-300",
    src: "https://images.unsplash.com/photo-1618222155830-fcacd23874e2?auto=format&fit=crop&w=1000&q=80",
    title: "Living room with white sofa and white sofa",
    description: "living room with white sofa and white sofa",
    style: "loft",
    room: "living_room",
    palette: "neutral",
    budget: "medium",
    lighting: "soft",
    material: "mixed",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "industrial",
    qualityScore: 6,
  },
  {
    id: "design-387",
    src: "https://images.unsplash.com/photo-1558442074-3c19857bc1dc?auto=format&fit=crop&w=1000&q=80",
    title: "Rectangular white coffee table near brown leather sofa",
    description: "rectangular white coffee table near brown leather sofa",
    style: "loft",
    room: "living_room",
    palette: "warm",
    budget: "medium",
    lighting: "ambient",
    material: "textile",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "industrial",
    qualityScore: 6,
  },
  {
    id: "design-392",
    src: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&w=1000&q=80",
    title: "Gray and white living room set",
    description: "gray and white living room set",
    style: "loft",
    room: "living_room",
    palette: "cool",
    budget: "medium",
    lighting: "soft",
    material: "mixed",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "industrial",
    qualityScore: 6,
  },
  {
    id: "design-353",
    src: "https://images.unsplash.com/photo-1540760029765-138c8f6d2eac?auto=format&fit=crop&w=1000&q=80",
    title: "Oval glass top table with armchairs",
    description: "oval glass top table with armchairs",
    style: "loft",
    room: "living_room",
    palette: "cool",
    budget: "medium",
    lighting: "ambient",
    material: "mixed",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "industrial",
    qualityScore: 6,
  },
  {
    id: "design-317",
    src: "https://images.unsplash.com/photo-1582037928769-181f2644ecb7?auto=format&fit=crop&w=1000&q=80",
    title: "White and blue floral throw pillows on white couch",
    description: "white and blue floral throw pillows on white couch",
    style: "loft",
    room: "living_room",
    palette: "cool",
    budget: "medium",
    lighting: "soft",
    material: "textile",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "industrial",
    qualityScore: 6,
  },
  {
    id: "design-464",
    src: "https://images.unsplash.com/photo-1600489000022-c2086d79f9d4?auto=format&fit=crop&w=1000&q=80",
    title: "White and brown kitchen cabinet",
    description: "white and brown kitchen cabinet",
    style: "loft",
    room: "kitchen",
    palette: "neutral",
    budget: "medium",
    lighting: "soft",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "industrial",
    qualityScore: 4,
  },
  {
    id: "design-398",
    src: "https://images.unsplash.com/photo-1633696376754-308dbb62e433?auto=format&fit=crop&w=1000&q=80",
    title: "A dining room with a table and chairs",
    description: "a dining room with a table and chairs",
    style: "loft",
    room: "dining_room",
    palette: "cool",
    budget: "medium",
    lighting: "ambient",
    material: "mixed",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "industrial",
    qualityScore: 4,
  },
  {
    id: "design-11",
    src: "https://images.unsplash.com/photo-1616047006789-b7af5afb8c20?auto=format&fit=crop&w=1000&q=80",
    title: "Brown wooden bed frame with white and brown bed linen",
    description: "brown wooden bed frame with white and brown bed linen",
    style: "loft",
    room: "bedroom",
    palette: "warm",
    budget: "medium",
    lighting: "soft",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "industrial",
    qualityScore: 4,
  },
  {
    id: "design-226",
    src: "https://images.unsplash.com/photo-1615529162924-f8605388461d?auto=format&fit=crop&w=1000&q=80",
    title: "White and brown wooden bed frame",
    description: "white and brown wooden bed frame",
    style: "loft",
    room: "bedroom",
    palette: "neutral",
    budget: "medium",
    lighting: "soft",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "industrial",
    qualityScore: 4,
  },
  {
    id: "design-413",
    src: "https://images.unsplash.com/photo-1592401526914-7e5d94a8d6fa?auto=format&fit=crop&w=1000&q=80",
    title: "Blue and white sofa near glass coffee table",
    description: "blue and white sofa near glass coffee table",
    style: "industrial",
    room: "living_room",
    palette: "cool",
    budget: "medium",
    lighting: "dramatic",
    material: "metal",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "industrial",
    qualityScore: 6,
  },
  {
    id: "design-419",
    src: "https://images.unsplash.com/photo-1591924141389-7875d935d3d1?auto=format&fit=crop&w=1000&q=80",
    title: "Gray sofa near glass table",
    description: "gray sofa near glass table",
    style: "industrial",
    room: "living_room",
    palette: "cool",
    budget: "medium",
    lighting: "dramatic",
    material: "metal",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "industrial",
    qualityScore: 6,
  },
  {
    id: "design-437",
    src: "https://images.unsplash.com/photo-1596204976717-1a9ff47f74ef?auto=format&fit=crop&w=1000&q=80",
    title: "Living room with white sofa and black flat screen tv",
    description: "living room with white sofa and black flat screen tv",
    style: "industrial",
    room: "living_room",
    palette: "cool",
    budget: "medium",
    lighting: "dramatic",
    material: "mixed",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "industrial",
    qualityScore: 6,
  },
  {
    id: "design-495",
    src: "https://images.unsplash.com/photo-1618219788702-20a1ef509691?auto=format&fit=crop&w=1000&q=80",
    title: "Orange throw pillow on white couch",
    description: "orange throw pillow on white couch",
    style: "industrial",
    room: "living_room",
    palette: "warm",
    budget: "medium",
    lighting: "ambient",
    material: "mixed",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "industrial",
    qualityScore: 6,
  },
  {
    id: "design-10",
    src: "https://images.unsplash.com/photo-1564078516393-cf04bd966897?auto=format&fit=crop&w=1000&q=80",
    title: "Gray padded chaise couch beside window",
    description: "gray padded chaise couch beside window",
    style: "industrial",
    room: "living_room",
    palette: "cool",
    budget: "medium",
    lighting: "daylight",
    material: "textile",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: true,
    hasPlants: false,
    floorType: "wood",
    theme: "industrial",
    qualityScore: 5,
  },
  {
    id: "design-6",
    src: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1000&q=80",
    title: "White and brown living room set",
    description: "white and brown living room set",
    style: "industrial",
    room: "living_room",
    palette: "neutral",
    budget: "medium",
    lighting: "soft",
    material: "mixed",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "industrial",
    qualityScore: 5,
  },
  {
    id: "design-472",
    src: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1000&q=80",
    title: "Photo of dining table and chairs inside room",
    description: "photo of dining table and chairs inside room",
    style: "industrial",
    room: "dining_room",
    palette: "cool",
    budget: "medium",
    lighting: "dramatic",
    material: "metal",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "industrial",
    qualityScore: 2,
  },
  {
    id: "design-490",
    src: "https://images.unsplash.com/photo-1556910638-6cdac31d44dc?auto=format&fit=crop&w=1000&q=80",
    title: "Woman standing in front of kitchen sink",
    description: "woman standing in front of kitchen sink",
    style: "industrial",
    room: "kitchen",
    palette: "neutral",
    budget: "medium",
    lighting: "soft",
    material: "mixed",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "industrial",
    qualityScore: 4,
  },
  {
    id: "design-55",
    src: "https://images.unsplash.com/photo-1562438668-bcf0ca6578f0?auto=format&fit=crop&w=1000&q=80",
    title: "Gray bed in bedroom",
    description: "gray bed in bedroom",
    style: "industrial",
    room: "bedroom",
    palette: "cool",
    budget: "medium",
    lighting: "soft",
    material: "mixed",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "industrial",
    qualityScore: 4,
  },
  {
    id: "design-81",
    src: "https://images.unsplash.com/photo-1594873604892-b599f847e859?auto=format&fit=crop&w=1000&q=80",
    title: "Black laptop computer on table",
    description: "black laptop computer on table",
    style: "industrial",
    room: "office",
    palette: "cool",
    budget: "medium",
    lighting: "dramatic",
    material: "metal",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "industrial",
    qualityScore: 5,
  },
  {
    id: "design-38",
    src: "https://images.unsplash.com/photo-1540638349517-3abd5afc5847?auto=format&fit=crop&w=1000&q=80",
    title: "Vacant brown fabric sofa",
    description: "vacant brown fabric sofa",
    style: "classic",
    room: "living_room",
    palette: "warm",
    budget: "high",
    lighting: "ambient",
    material: "textile",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 6,
  },
  {
    id: "design-166",
    src: "https://images.unsplash.com/photo-1632829882891-5047ccc421bc?auto=format&fit=crop&w=1000&q=80",
    title: "A living room filled with furniture and a fire place",
    description: "a living room filled with furniture and a fire place",
    style: "classic",
    room: "living_room",
    palette: "warm",
    budget: "high",
    lighting: "ambient",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 7,
  },
  {
    id: "design-28",
    src: "https://images.unsplash.com/photo-1506377295352-e3154d43ea9e?auto=format&fit=crop&w=1000&q=80",
    title: "White study lamp on top of white wooden end table beside gray fabric sofa",
    description: "white study lamp on top of white wooden end table beside gray fabric sofa",
    style: "classic",
    room: "living_room",
    palette: "warm",
    budget: "high",
    lighting: "ambient",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 5,
  },
  {
    id: "design-52",
    src: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=1000&q=80",
    title: "A living room filled with furniture and a large window",
    description: "a living room filled with furniture and a large window",
    style: "classic",
    room: "living_room",
    palette: "warm",
    budget: "high",
    lighting: "daylight",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: true,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 5,
  },
  {
    id: "design-103",
    src: "https://images.unsplash.com/photo-1600054648630-e10e710825f6?auto=format&fit=crop&w=1000&q=80",
    title: "White and brown wooden bed frame",
    description: "white and brown wooden bed frame",
    style: "classic",
    room: "bedroom",
    palette: "warm",
    budget: "high",
    lighting: "soft",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 4,
  },
  {
    id: "design-492",
    src: "https://images.unsplash.com/photo-1519643381401-22c77e60520e?auto=format&fit=crop&w=1000&q=80",
    title: "White wooden dining table set during daytime",
    description: "white wooden dining table set during daytime",
    style: "classic",
    room: "dining_room",
    palette: "neutral",
    budget: "high",
    lighting: "daylight",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: true,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 4,
  },
  {
    id: "design-395",
    src: "https://images.unsplash.com/photo-1463797221720-6b07e6426c24?auto=format&fit=crop&w=1000&q=80",
    title: "Brown wooden dining table near white and brown mini bar",
    description: "brown wooden dining table near white and brown mini bar",
    style: "classic",
    room: "dining_room",
    palette: "warm",
    budget: "high",
    lighting: "ambient",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 3,
  },
  {
    id: "design-29",
    src: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1000&q=80",
    title: "White mattress beside sectional sofa",
    description: "white mattress beside sectional sofa",
    style: "classic",
    room: "bedroom",
    palette: "neutral",
    budget: "high",
    lighting: "soft",
    material: "textile",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 5,
  },
  {
    id: "design-15",
    src: "https://images.unsplash.com/photo-1634712282287-14ed57b9cc89?auto=format&fit=crop&w=1000&q=80",
    title: "A blue chair and a yellow lamp in a white room",
    description: "a blue chair and a yellow lamp in a white room",
    style: "classic",
    room: "living_room",
    palette: "bright",
    budget: "high",
    lighting: "ambient",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 5,
  },
  {
    id: "design-39",
    src: "https://images.unsplash.com/photo-1596079890687-58c51d24889a?auto=format&fit=crop&w=1000&q=80",
    title: "White wooden table with chairs",
    description: "white wooden table with chairs",
    style: "classic",
    room: "dining_room",
    palette: "neutral",
    budget: "high",
    lighting: "soft",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 5,
  },
  {
    id: "design-45",
    src: "https://images.unsplash.com/photo-1633505899118-4ca6bd143043?auto=format&fit=crop&w=1000&q=80",
    title: "A living room filled with furniture and a large window",
    description: "a living room filled with furniture and a large window",
    style: "luxury",
    room: "living_room",
    palette: "neutral",
    budget: "high",
    lighting: "dramatic",
    material: "stone",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: true,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 6,
  },
  {
    id: "design-67",
    src: "https://images.unsplash.com/photo-1616137422495-1e9e46e2aa77?auto=format&fit=crop&w=1000&q=80",
    title: "Gray and white sofa set",
    description: "gray and white sofa set",
    style: "luxury",
    room: "living_room",
    palette: "cool",
    budget: "high",
    lighting: "dramatic",
    material: "mixed",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 5,
  },
  {
    id: "design-73",
    src: "https://images.unsplash.com/photo-1631510390389-c1e4fb20ff31?auto=format&fit=crop&w=1000&q=80",
    title: "White and gray sofa chair near window",
    description: "white and gray sofa chair near window",
    style: "luxury",
    room: "living_room",
    palette: "neutral",
    budget: "high",
    lighting: "daylight",
    material: "textile",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: true,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 5,
  },
  {
    id: "design-89",
    src: "https://images.unsplash.com/photo-1603192399946-8bbb0703cfc4?auto=format&fit=crop&w=1000&q=80",
    title: "White throw pillow on white couch",
    description: "white throw pillow on white couch",
    style: "luxury",
    room: "living_room",
    palette: "neutral",
    budget: "high",
    lighting: "soft",
    material: "textile",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 5,
  },
  {
    id: "design-104",
    src: "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1000&q=80",
    title: "White steel chair in front round table on white rug",
    description: "white steel chair in front round table on white rug",
    style: "luxury",
    room: "living_room",
    palette: "neutral",
    budget: "high",
    lighting: "dramatic",
    material: "stone",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 5,
  },
  {
    id: "design-105",
    src: "https://images.unsplash.com/photo-1616137148650-4aa14651e02b?auto=format&fit=crop&w=1000&q=80",
    title: "White and black throw pillow on white couch",
    description: "white and black throw pillow on white couch",
    style: "luxury",
    room: "living_room",
    palette: "cool",
    budget: "high",
    lighting: "soft",
    material: "textile",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 5,
  },
  {
    id: "design-204",
    src: "https://images.unsplash.com/photo-1632583824020-937ae9564495?auto=format&fit=crop&w=1000&q=80",
    title: "A modern kitchen with a bar and stools",
    description: "a modern kitchen with a bar and stools",
    style: "luxury",
    room: "kitchen",
    palette: "neutral",
    budget: "high",
    lighting: "dramatic",
    material: "stone",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 3,
  },
  {
    id: "design-88",
    src: "https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&w=1000&q=80",
    title: "Brown wooden chair beside plant",
    description: "brown wooden chair beside plant",
    style: "luxury",
    room: "living_room",
    palette: "warm",
    budget: "high",
    lighting: "daylight",
    material: "wood",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: true,
    hasPlants: true,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 5,
  },
  {
    id: "design-177b",
    src: "https://images.unsplash.com/photo-1631701601945-414a32dbef47?auto=format&fit=crop&w=1000&q=80",
    title: "A living room with luxury furnishings and mirror",
    description: "a living room with luxury furnishings and mirror",
    style: "luxury",
    room: "living_room",
    palette: "neutral",
    budget: "high",
    lighting: "dramatic",
    material: "stone",
    orientation: "horizontal",
    dominantColor: "neutral",
    hasWindow: false,
    hasPlants: false,
    floorType: "wood",
    theme: "elegant",
    qualityScore: 6,
  },
];
